const DOMSelectors = {
  spacing: document.querySelector(".spacing"),
};
const recipes = [
  {
    name: "Spaghetti Carbonara",
    image: "/img1.jpg",
    ingredients: [
      "spaghetti",
      "eggs",
      "pancetta",
      "parmesan",
      "black pepper",
      "garlic",
    ],
    genre: "Italian",
  },
  {
    name: "Chicken Tikka Masala",
    image: "/img2.jpg",
    ingredients: [
      "chicken",
      "yogurt",
      "tomato sauce",
      "onions",
      "garlic",
      "spices",
    ],
    genre: "Indian",
  },
  {
    name: "Caesar Salad",
    image: "/img3.jpg",
    ingredients: ["romaine lettuce", "parmesan", "croutons", "Caesar dressing"],
    genre: "American",
  },
  {
    name: "Sushi Rolls",
    image: "/img4.jpg",
    ingredients: [
      "sushi rice",
      "nori",
      "salmon",
      "avocado",
      "cucumber",
      "soy sauce",
    ],
    genre: "Japanese",
  },
  {
    name: "Tacos",
    image: "/img5.jpg",
    ingredients: [
      "taco shells",
      "ground beef",
      "lettuce",
      "cheese",
      "tomato",
      "sour cream",
    ],
    genre: "Mexican",
  },
  {
    name: "Beef Wellington",
    image: "/img6.jpg",
    ingredients: [
      "beef tenderloin",
      "puff pastry",
      "mushrooms",
      "prosciutto",
      "egg",
    ],
    genre: "British",
  },
  {
    name: "Lasagna",
    image: "/img7.jpg",
    ingredients: [
      "lasagna noodles",
      "ground beef",
      "ricotta",
      "mozzarella",
      "tomato sauce",
    ],
    genre: "Italian",
  },
  {
    name: "Ramen",
    image: "/img8.jpg",
    ingredients: ["ramen noodles", "pork", "egg", "broth", "scallions", "nori"],
    genre: "Japanese",
  },
  {
    name: "Vegetable Stir Fry",
    image: "/img9.jpg",
    ingredients: [
      "broccoli",
      "carrot",
      "bell pepper",
      "soy sauce",
      "garlic",
      "ginger",
    ],
    genre: "Chinese",
  },
  {
    name: "Chicken Alfredo",
    image: "/img10.jpg",
    ingredients: [
      "fettuccine",
      "chicken breast",
      "heavy cream",
      "parmesan",
      "garlic",
      "butter",
    ],
    genre: "Italian",
  },
  {
    name: "Falafel",
    image: "/img11.jpg",
    ingredients: [
      "chickpeas",
      "garlic",
      "parsley",
      "onions",
      "cumin",
      "coriander",
    ],
    genre: "Middle Eastern",
  },
  {
    name: "Eggplant Parmesan",
    image: "/img12.jpg",
    ingredients: [
      "eggplant",
      "tomato sauce",
      "mozzarella",
      "parmesan",
      "bread crumbs",
    ],
    genre: "Italian",
  },
  {
    name: "Banh Mi",
    image: "/img13.jpg",
    ingredients: [
      "baguette",
      "pork",
      "pickled vegetables",
      "cilantro",
      "jalapenos",
      "mayonnaise",
    ],
    genre: "Vietnamese",
  },
  {
    name: "Peking Duck",
    image: "/img14.jpg",
    ingredients: ["duck", "hoisin sauce", "pancakes", "scallions", "cucumber"],
    genre: "Chinese",
  },
  {
    name: "Pad Thai",
    image: "/img15.jpg",
    ingredients: ["rice noodles", "shrimp", "tofu", "peanuts", "lime", "egg"],
    genre: "Thai",
  },
  {
    name: "Moussaka",
    image: "/img16.jpg",
    ingredients: [
      "eggplant",
      "ground lamb",
      "tomato",
      "bechamel sauce",
      "cheese",
    ],
    genre: "Greek",
  },
  {
    name: "Shakshuka",
    image: "/img17.jpg",
    ingredients: ["eggs", "tomatoes", "onions", "peppers", "garlic", "spices"],
    genre: "Middle Eastern",
  },
  {
    name: "Paella",
    image: "/img18.jpg",
    ingredients: [
      "rice",
      "seafood",
      "chicken",
      "saffron",
      "peas",
      "bell peppers",
    ],
    genre: "Spanish",
  },
  {
    name: "Chicken Parmesan",
    image: "/img19.jpg",
    ingredients: [
      "chicken breast",
      "tomato sauce",
      "mozzarella",
      "parmesan",
      "spaghetti",
    ],
    genre: "Italian",
  },
  {
    name: "Pasta Primavera",
    image: "/img20.jpg",
    ingredients: [
      "pasta",
      "tomatoes",
      "zucchini",
      "bell peppers",
      "parmesan",
      "garlic",
    ],
    genre: "Italian",
  },
];

export { DOMSelectors };
export { recipes };
