const DOMSelectors = {};
const recipes = [
  {
    name: "Spaghetti Carbonara",
    image: "https://example.com/spaghetti-carbonara.jpg",
    ingredients: [
      "spaghetti",
      "eggs",
      "pancetta",
      "parmesan",
      "black pepper",
      "garlic",
    ],
    genre: "Italian",
  },
  {
    name: "Chicken Tikka Masala",
    image: "https://example.com/chicken-tikka-masala.jpg",
    ingredients: [
      "chicken",
      "yogurt",
      "tomato sauce",
      "onions",
      "garlic",
      "spices",
    ],
    genre: "Indian",
  },
  {
    name: "Caesar Salad",
    image: "https://example.com/caesar-salad.jpg",
    ingredients: ["romaine lettuce", "parmesan", "croutons", "Caesar dressing"],
    genre: "American",
  },
  {
    name: "Sushi Rolls",
    image: "https://example.com/sushi-rolls.jpg",
    ingredients: [
      "sushi rice",
      "nori",
      "salmon",
      "avocado",
      "cucumber",
      "soy sauce",
    ],
    genre: "Japanese",
  },
  {
    name: "Tacos",
    image: "https://example.com/tacos.jpg",
    ingredients: [
      "taco shells",
      "ground beef",
      "lettuce",
      "cheese",
      "tomato",
      "sour cream",
    ],
    genre: "Mexican",
  },
  {
    name: "Beef Wellington",
    image: "https://example.com/beef-wellington.jpg",
    ingredients: [
      "beef tenderloin",
      "puff pastry",
      "mushrooms",
      "prosciutto",
      "egg",
    ],
    genre: "British",
  },
  {
    name: "Lasagna",
    image: "https://example.com/lasagna.jpg",
    ingredients: [
      "lasagna noodles",
      "ground beef",
      "ricotta",
      "mozzarella",
      "tomato sauce",
    ],
    genre: "Italian",
  },
  {
    name: "Ramen",
    image: "https://example.com/ramen.jpg",
    ingredients: ["ramen noodles", "pork", "egg", "broth", "scallions", "nori"],
    genre: "Japanese",
  },
  {
    name: "Vegetable Stir Fry",
    image: "https://example.com/vegetable-stir-fry.jpg",
    ingredients: [
      "broccoli",
      "carrot",
      "bell pepper",
      "soy sauce",
      "garlic",
      "ginger",
    ],
    genre: "Chinese",
  },
  {
    name: "Chicken Alfredo",
    image: "https://example.com/chicken-alfredo.jpg",
    ingredients: [
      "fettuccine",
      "chicken breast",
      "heavy cream",
      "parmesan",
      "garlic",
      "butter",
    ],
    genre: "Italian",
  },
  {
    name: "Falafel",
    image: "https://example.com/falafel.jpg",
    ingredients: [
      "chickpeas",
      "garlic",
      "parsley",
      "onions",
      "cumin",
      "coriander",
    ],
    genre: "Middle Eastern",
  },
  {
    name: "Eggplant Parmesan",
    image: "https://example.com/eggplant-parmesan.jpg",
    ingredients: [
      "eggplant",
      "tomato sauce",
      "mozzarella",
      "parmesan",
      "bread crumbs",
    ],
    genre: "Italian",
  },
  {
    name: "Banh Mi",
    image: "https://example.com/banh-mi.jpg",
    ingredients: [
      "baguette",
      "pork",
      "pickled vegetables",
      "cilantro",
      "jalapenos",
      "mayonnaise",
    ],
    genre: "Vietnamese",
  },
  {
    name: "Peking Duck",
    image: "https://example.com/peking-duck.jpg",
    ingredients: ["duck", "hoisin sauce", "pancakes", "scallions", "cucumber"],
    genre: "Chinese",
  },
  {
    name: "Pad Thai",
    image: "https://example.com/pad-thai.jpg",
    ingredients: ["rice noodles", "shrimp", "tofu", "peanuts", "lime", "egg"],
    genre: "Thai",
  },
  {
    name: "Moussaka",
    image: "https://example.com/moussaka.jpg",
    ingredients: [
      "eggplant",
      "ground lamb",
      "tomato",
      "bechamel sauce",
      "cheese",
    ],
    genre: "Greek",
  },
  {
    name: "Shakshuka",
    image: "https://example.com/shakshuka.jpg",
    ingredients: ["eggs", "tomatoes", "onions", "peppers", "garlic", "spices"],
    genre: "Middle Eastern",
  },
  {
    name: "Paella",
    image: "https://example.com/paella.jpg",
    ingredients: [
      "rice",
      "seafood",
      "chicken",
      "saffron",
      "peas",
      "bell peppers",
    ],
    genre: "Spanish",
  },
  {
    name: "Chicken Parmesan",
    image: "https://example.com/chicken-parmesan.jpg",
    ingredients: [
      "chicken breast",
      "tomato sauce",
      "mozzarella",
      "parmesan",
      "spaghetti",
    ],
    genre: "Italian",
  },
  {
    name: "Pasta Primavera",
    image: "https://example.com/pasta-primavera.jpg",
    ingredients: [
      "pasta",
      "tomatoes",
      "zucchini",
      "bell peppers",
      "parmesan",
      "garlic",
    ],
    genre: "Italian",
  },
];

export { DOMSelectors };
export { recipes };
